FROM node:18-alpine AS build
WORKDIR /app
COPY portal/package*.json ./
RUN npm install
COPY portal/ .
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY portal/nginx.conf /etc/nginx/conf.d/default.conf
