version: '3.8'

services:
  nginx:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - dnaresearch_prod

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
      target: production
    environment:
      - DATABASE_URL=postgresql://prod_user:${POSTGRES_PASSWORD}@postgres:5432/dnaresearch_prod
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - DEBUG=false
    depends_on:
      - postgres
      - redis
      - minio
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dnaresearch_prod

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=prod_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=dnaresearch_prod
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./init-scripts/init-prod-db.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prod_user -d dnaresearch_prod"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dnaresearch_prod

  redis:
    image: redis:7-alpine
    volumes:
      - redis_prod_data:/data
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dnaresearch_prod

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - minio_prod_data:/data
    command: server /data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dnaresearch_prod

volumes:
  postgres_prod_data:
  redis_prod_data:
  minio_prod_data:

networks:
  dnaresearch_prod:
    driver: bridge